### PR TITLE
Support data URIs with webp image data.

### PR DESCRIPTION
**Pull request by DirtyHairy**
Hi Darryl!

This pull request adds support for data URIs containing webp encoded image data. Thanks alot for your plugin :smirk:

Cheers
    -Christian

### CODE REVIEW

**Comment by dpogue** [comment]
Thanks a lot for making the plugin better!

The change looks good, I haven't had a chance to test it yet but I will aim to do that tomorrow and get this into a new release :)

**Comment by dpogue** [comment]
I'm trying this with an image, and it doesn't seem to be loading in the UIWebView:

``` html
<img src="data:image/webp;base64,UklGRs4CAABXRUJQVlA4WAoAAAAQAAAARwAARwAAQUxQSHYCAAABF+QgkiRFuuyZ2Wfwb/dAQ0TkFnFeLuruT4j9Lg5ZH/vIGlFRlLRjWUSXgkig0In9VknGGbAFgC0kZc+2bdu2bdu+tXGXX99ek3Sf7i2i/xMA/8qpTWMbd3Z3KOS2322MNabESM7wdQiJwauhbPNqjiPIGj6qMqv2BgWvq83J30PhnVxDurwo7mkzIXEZjVxIEMs4R0NP04SyntHYxyyRjGckf0/U5yUk5NdP2kj4mC6QeI5Ua7sF/rR02il4lsC3hNTNFNBO3abgPFsXUqeAPEPBVqZ8L2UTGHconhyeXSRaUzjSHATcYqlFagcok4afAoHHwUQFdFOwiuOG8m1RFL2j8rVAYbFTLhlqkDoB0Unv+OdLQhRMUbCSdkyqVwyj5oCikXRIyomQ8hRPOg+KQlI4izKM5ARFQMenSCRhP+WaxuhXxNMuCKkhA+4VJbRAsl4TGtin6KFhg96YAU8Jin2GUb0NuY9ciC6NMKzp3Yl95kN03BUy3urZpb4KQDmPnFY9t5CtGJTTyOrSC8k4S0A5gbxBc35rQDmOJrhFVkA5iNwuPbtEqEBR/cNm1buT2IfouA9kv9XbkOhVtCD/qt6YRJliXWBEr1EiRfEmUK+XEhIApZcvkKwHV2K/fOdAHBIQ76PkhGMllEmBo1g5AHJVrJTT4Do2zoGxOiZ+KzhghwuUXOvAmusxz53FA23mNQP3omlzwJ5watZJPB+kP5p0nwqSWY8M7PeZIJt+ZspJKkgnLJgxGw8Gtnnk3M1gZs620O96FhhbdSlxXglGVx6GeUIHFWB8Vv9FkBI478uE2ExuGF27tbqCQZf1dnWkLgn+lQFWUDggMgAAABAEAJ0BKkgASAA+bTaZSaQjIqEhSACADYlpAAAJ8aNGjRo0aNGjRn4AAP77nMAAAAAA">
```

Is this how you were testing?

**Comment by DirtyHairy** [comment]
Yeah, this was basically what I was doing. I just doublechecked and inserted your image tag into my test app; I can see the image just fine. I am building with cordova iOS 4.1.1, XCode 7.3 and running on the iPhone 5 simulator.

**Comment by dpogue** [comment]
hmm, it does work in iOS8 and iOS9, but shows a missing image in iOS10. All using UIWebView (since WKWebView doesn't allow URL interception).

The issue is that the data URI never hits the NSURLProtocol in iOS10.

**Comment by dpogue** [comment]
Anyways, this does work for <= iOS9, so let's get it merged :)

**Comment by DirtyHairy** [comment]
Too bad, thanks for merging anyway. I might have another look at this when our project reaches the point where we actually need it --- maybe there is a way to route data URLs through the handler on iOS 10.

**Pull request merged**
